### ISSUE TITLE
Error Executing Example Script

### ISSUE THREAD

**Issue by jarosado0911** [UG4/app_Examples#2]
Hello, I am attempting to execute `mesh_sample_3D_box_geometry.lua` however, I am receiving the following error:
```
tetrahedralizing using 'tetgen' by Hang Si... <dbg>
<dbg> running ug::Tetrahedralize

 % EXCEPTION on Proc 0: UGError thrown
 %   Error traceback (innermost first):
 %   0:
 %      PerformTetrahedralization: Tetgen is not available in the current build.
 %      Recompile with Tetgen support to use tetrahedralization.
 %
 %      [at ...\lib_grid\algorithms\grid_generation\tetrahedralization.cpp:293]
 % In CALL to function 'Tetrahedralize(Mesh* mesh, number quality, bool preserve outer, bool preserve all, bool separate volumes, bool append subsets at end, integer verbosity)'
 %    ARGS: (pointer 0000018234FFF130, double 1.414, bool 0, bool 0, bool 1, bool 1, int 0)
 % In FILE: @test.lua:129
 % At LINE: 'Tetrahedralize(obj, 1.414, false, false, true, true, 0)'
LUA-ERROR! Call stack:
   1  @test.lua:129   Tetrahedralize(obj, 1.414, false, false, true, true, 0)   
 % ABORTING script parsing.
```

I have compiled ug4 with tetgen on, below is the cmake output:
```
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
--
-- Info: Current options:
-- Info: TARGET:            ugshell (options are: ugshell, libug4, vrl, vrlgrid, libgrid, gridshell, ugplugin, amg, luashell)
-- Info: DIM:               ALL (options are: 1, 2, 3, ALL, "1;2", "1;3", "2;3")
-- Info: CPU:               1 (options are: 1, 2, 3, 4, 5, VAR, ALL, "2;4", "1;3;4" , ...)
-- Info: PRECISION:         double (options are: single, double)
-- Info: STATIC_BUILD:      ON (options are: ON, OFF)
-- Info: DEBUG:             OFF (options are: ON, OFF)
-- Info: DEBUG_LOGS:        OFF (options are: ON, OFF)
-- Info: PARALLEL:          OFF (options are: ON, OFF)
-- Info: PCL_DEBUG_BARRIER: OFF (options are: ON, OFF)
-- Info: PROFILER:          None (options are: None, Shiny, Scalasca, Vampir, ScoreP)
-- Info: PROFILE_PCL:       OFF (options are: ON, OFF)
-- Info: CPU_FREQ:          OFF (options are: ON, OFF)
-- Info: PROFILE_BRIDGE:    OFF (options are: ON, OFF)
-- Info: LAPACK:            OFF (options are: ON, OFF)
-- Info: BLAS:              OFF (options are: ON, OFF)
-- Info: INTERNAL_BOOST:    ON (options are: ON, OFF)
-- Info: EMBEDDED_PLUGINS   ON (options are: ON, OFF)
-- Info: COMPILE_INFO       ON (options are: ON, OFF)
-- Info: USE_LUA2C          OFF (options are: ON, OFF)
-- Info: USE_LUAJIT         OFF (options are: ON, OFF)
--
-- Info: External libraries (path which contains the library or ON if you used uginstall):
-- Info: TETGEN:
-- Info: HLIBPRO:
-- Info: USE_JSON:          OFF (options are: ON, OFF)
-- Info: USE_XEUS:          OFF (options are: ON, OFF)
--
-- Info: C   Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe (ID: MSVC)
-- Info: C++ Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe (ID: MSVC)
--
-- Info: Using CPU Algebra.
-- Info: compiling with cxx flags:  /bigobj /MD /O2 /Ob2 /DNDEBUG
-- Info: compiling with c flags:  /bigobj /MD /O2 /Ob2 /DNDEBUG
-- Info: Trying to activate 'CMAKE_CXX_STANDARD 11'
-- Info: Not using LAPACK, use -DLAPACK=ON to enable.
-- Info: Not using BLAS, use -DBLAS=ON to enable.
-- Info: Internal Boost
-- Info: Including Boost from C:/Users/jaros/ug4/ugcore/cmake/../../externals/BoostForUG4/
-- Info: COMPILE_INFO enabled. Causes relinking on each run of make.
--
-- Info: Enabled plugins:
--       ConvectionDiffusion, Electromagnetism, MembranePotentialMapping,
--       NavierStokes, ProMesh, SmallStrainMechanics,
--       cable_neuron, neuro_collection,
-- Info: Disabled plugins:
--       LuaShell, Neurolucida, SkinLayerGenerator,
--
-- Hint: To enable/disable a plugin 'PLUGIN_NAME' use the cmake option: -DPLUGIN_NAME=ON/OFF
--
-- Additional options for the MembranePotentialMapping (-DMPM) plugin:
--       Testsuite:       OFF (options are: ON, OFF)
--       VGCC:            OFF (options are: 0 (none), 1 (simple), 2 (default))
--       OpenMP:          OFF (options are: ON, OFF)
--       NEURON_REVISION: ON (options are: ON, OFF)
--       NEURON_STATIC:   ON (options are: ON, OFF)
--       SHELLTYPE:       OFF (options are none, readline)
--       NEURON:          OFF (turn Neuron API on using -DMPMNEURON=/path/to/NEURON/installation
-- Info: Additional options for the ProMesh plugin:
-- Info:   DEBUG_PATH   Specify a path to which debug output may be written. Only for development builds.
--
-- Additional options (-DCN) for the cable_neuron plugin
--       Testsuite:     OFF (options are: ON, OFF)
--       Cpp11Features: ON (options are: ON, OFF)
--       Compiler does not support C++11: HOC import will not be available.
--
-- Additional options for the neuro_collection plugin (-DNC for setting options):
--       Testsuite:   OFF (options are: ON, OFF)
--
-- Tools:
--   - tetgen (ON)
--
-- Info: SHELLTYPE: simple (options are: linenoise, readline, simple)
--
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/jaros/ug4/build_vs

```
inside  `mesh_sample_3D_box_geometry.lua` when I comment out the  tetrahedralize line the code runs fine.

My machine is Windows 10 (os build 19042.1237) and I build using Microsoft Visual Studio Community 2019
Version 16.8.6, when I compile and build ug4 I followed the directions in this issue: https://github.com/UG4/ughub/issues/18

aside from this issue ug4 runs fine.
Do I need to provide a path for `-DTETGEN=<...>` when executing cmake?
Do I need to change 'TARGET'?

Thanks 😊 
If I need to provide more info, or my question is not clear please let me know I am happy to oblige 😊

**Comment by sreiter** [comment]
Thanks for reporting the issue! Apparently, this also happens on my Ubuntu installation (through WSL2).
Tetgen was moved out of the sources into a separate repository at some point in time. Now we compile it as a tool, i.e., not linking against it but instead call it as a separate program - mainly due to licensing issues.
I think we have to check the implementation and make sure that it also uses the new way of calling tetgen. I'll have a look.
Regards,
Sebastian

**Comment by sreiter** [comment]
I looked into the sources again. Actually, there was an option to link custom tetgen libraries to ug4 by specifying the path to that library using the TETGEN option you mentioned above. However, this is rather cumbersome and prone to error.

We also offer the tool `tetgen`, which you installed and enabled in cmake. However, this only builds an executable to be used from the commandline or from the ProMesh application (not the plugin).

I thus decided to slightly enhance the tool so that the library that's being built can be linked with ug4, too. Since tetgen is under the GPL, this should only ever be done for development/local builds, not for redistribution.

I opened this merge request on ugcore: https://github.com/UG4/ugcore/pull/57

And already slightly enhanced the tetgen tool: https://github.com/UG4/tool_tetgen/commit/91c7e432773ac03ab12714c60ee3600cbe81ec87

**Comment by sreiter** [comment]
I just merged the corresponding merge request to ugcore. It would be great if you could confirm whether it works for you.
Please make sure to update all related packages, ideally through `ughub git pull`.
On related news - I also fixed Windows Visual Studio builds by now always writing binaries to `bin` instead of `bin/Release` or `bin/Debug`. It should no longer be necessary to set those paths manually.

**Comment by jarosado0911** [comment]
@sreiter thank you for the update,  I tried out on my Windows machine,  it looks like it works, I was able to run ```mesh_sample_3D_box_geometry.lua``` and it produced the tetrahedralized geometry
![image](https://user-images.githubusercontent.com/57325500/134273978-3a6f88e8-e6e9-45f5-88b0-e4c0f76a9b32.png)

also as you indicated the binaries are no longer being placed in ```bin/Release``` but inside ```bin```
Thanks 😃

**Comment by jarosado0911** [comment]
Note, thank you for pointing out the ```ughub git pull``` that saved me time  --> ```ughub git pull`` git pulls everything?

Note, I also tried it on my WSL and all works. 😄

**Comment by sreiter** [comment]
Great that it works now. Thanks for confirming!
Yes, indeed, `ughub git pull` will perform `git pull` on all installed packages. You may pass other git commands even with corresponding arguments to `ughub git ...`.

From the ughub docu:
```
> ughub help git
Usage: ughub git COMMAND [GIT-OPTIONS] [--- [PACKAGE_1 [PACKAGE_2 [...]]]]

  Executes 'git COMMAND GIT-OPTIONS' on installed packages.
  COMMAND has to be a valid git-command. See 'git help' for valid git-commands.
  If PACKAGE_1,...,PACKAGE_N is specified after the separator '---' then
  'git COMMAND GIT-OPTIONS' will be executed on the specified packages only.
  If the separator or PACKAGE_1 was not specified, then the operation
  is performed for all installed packages.
```
